### ISSUE TITLE
Generate the `soy.js` for the tests

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay/liferay-npm-tools#106]
There is a case of the Forms team that they need create `.soy` files inside the tests folder and for this npm-scripts need to look there to be able to generate the `.soy.js` files.

We just look at the `src` folder, maybe we should add a glob?

https://github.com/liferay/liferay-npm-tools/blob/master/packages/liferay-npm-scripts/src/presets/standard/index.js#L14

**Comment by wincent** [comment]
I think we should be careful about adding that to the default. A lower-risk version would be to add an `npmscripts.config.js` file to the forms project only, with a pretty specific path. Perhaps that is what you meant. In any case, I would want to make sure that it doesn't have any other unintended side-effects (because there are [multiple tools that end up using that "build" glob](https://github.com/liferay/liferay-npm-tools/blob/25733d82dbab8b1278743d653799a2682c832359/packages/liferay-npm-scripts/src/scripts/build.js), like `babel`, `liferay-npm-bundler`, `liferay-npm-bridge-generator`, and `webpack`, in addition to soy.

**Comment by matuzalemsteles** [comment]
Yeah, maybe that'll work out. One problem is that the structure of the tests are in the root of the module along with `src`, if it were to solve this with the path it would be something like: `./` probably would have problems, it would generate the `.soy` files of classes and dependencies in `node_modules` that we probably did not want.

````
./src/...
./tests/...
```

**Comment by wincent** [comment]
Can youy provide a link to the module and files you're talking about? Our tests are supposed to be in a standard location ("test/", next to "src/"), in the top level of the module (see: https://github.com/liferay/liferay-npm-tools/pull/103 and https://github.com/liferay/liferay-npm-tools/issues/95).

**Comment by matuzalemsteles** [comment]
Yeah, they're at the top level of the module.
https://github.com/liferay/liferay-portal/tree/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web

**Comment by wincent** [comment]
Closing this one due to inactivity and because we aren't investing in Soy at all at this point. If there is still a demand for it, we can re-open this issue over at: https://github.com/liferay/liferay-frontend-projects/issues
