### ISSUE TITLE
Include the module name at the end of the classname when generating TEST-frontend-js.xml

### ISSUE THREAD

**Issue by john-co** [liferay/liferay-npm-tools#136]
Modify TEST-frontend-js.xml output to include the module name within testcase classname.

See https://github.com/john-co/liferay-portal/pull/140/commits/f618e23fc0dace5a91995c01dba47926faac4f2b

**Comment by wincent** [comment]
@john-co: can you help me understand a bit what this issue is about?

The module name is already in the classname; in the example you gave, I see you added ".[frontend-taglib]" at the end, but it is already in the name, at the start ("frontend-taglib.frontend-taglib-clay.test.management_toolbar").

The code that extracts it is [here](https://github.com/liferay/liferay-npm-tools/blob/3aabc3bb09cfc47145078e9337325fc940d27975/packages/liferay-jest-junit-reporter/src/index.js#L20-L22).

What exactly is required here?

**Comment by john-co** [comment]
Hi @wincent,

Adding a .${string} at the end of the classname provides the proposed test result output in the screenshot below:

![Selection_029](https://user-images.githubusercontent.com/35235266/60449273-235e3e00-9bdc-11e9-8f49-94a56a49d68e.png)
Left side is proposed, right side is current.

A live example can be found here: https://github.com/john-co/liferay-portal/pull/141

It doesn't matter what text it is really to get it to display the error like on the left side, it just needs an extra string. But to provide some useful info I thought displaying [${module name}] would be good to show which module the failing test belongs to on github without diving too deep into jenkins to figure out more info.

**Comment by john-co** [comment]
Hi @wincent, let me know if you need more context.
