### ISSUE TITLE
Apply general formatting guidelines

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-npm-tools#32]
While this project is used to enforce consistent build processes like linting and formatting, it itself doesn't follow neither. We should either use `liferay-npm-tools` to lint and format itself or at the very list follow the rest of other `out-of-Portal` projects.

**Comment by wincent** [comment]
Recent examples of current "best practice":

- Use "eslint-config-liferay" ([example](https://github.com/liferay/alloy-editor/blob/934bb406b32125a838fee438cb6f06dccb0bcc5c/package.json#L17))
- Use "prettier" ([example](https://github.com/liferay/alloy-editor/blob/934bb406b32125a838fee438cb6f06dccb0bcc5c/package.json#L43))

Example "package.json" scripts (these ones snipped from alloy-editor, but similar ones in liferay-js-themes-toolkit, liferay-amd-loader etc):

```
"format": "prettier --write -- '*.js' '{scripts,src,test}/**/*.{js,jsx}'",
"format:changed": "git ls-files -mz *.js -- 'scripts/*.js' 'src/*.js' 'src/*.jsx' 'test/*.js' 'test/*.jsx' | xargs -0 prettier --write --",
"format:check": "prettier --list-different -- '*.js' '{scripts,src,test}/**/*.{js,jsx}'",
"lint": "eslint 'src/**/*.{js,jsx}'",
"lint:changed": "git ls-files -mz 'src/*.js' 'src/*.jsx' | xargs -0 eslint",
"lint:fix": "eslint --fix 'src/**/*.{js,jsx}'",
"lint:quiet": "eslint --quiet 'src/**/*.{js,jsx}'",
```

**Comment by bryceosterhaus** [comment]
I went ahead and added `eslint-config-liferay` and using `prettier-eslint`.

**Comment by wincent** [comment]
@bryceosterhaus: One thing I've found in other projects is that `prettier-eslint-cli` has some unexpected behaviors. For example, running `format` ends up being equivalent to `eslint --fix`, which is surprising to say the least (because it can do stuff like adding license headers to files; not something I expect when running prettier). So in other projects, I swapped to `prettier` directly, which doesn't have this problem; examples:

- https://github.com/liferay/liferay-amd-loader/pull/194/commits/30e1dfdf1b516b147d890834fe303b0cbc507fcd
- https://github.com/liferay/liferay-npm-build-tools/pull/290/commits/a11a7c7189291ef192f9e59b7c61e74087bf74ac

**Comment by bryceosterhaus** [comment]
Yeah `prettier-eslint` essentially runs something like `prettier && eslint --fix`. I'm fine with using it that way since when I format I typically want both the prettier rules and eslint rules enforced, however, this could just be because I am used to using it this way. The last few projects I've used have all used `prettier-eslint`, clay is using it as well. I never seemed to have problems with it.

**Comment by wincent** [comment]
Formatting and linting should be orthogonal concerns though: formatting makes things *look* right, and linting identifies (and possibly corrects) *mistakes* or things that could lead to issues. That's why we use [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier), to turn "off all rules that are unnecessary or might conflict with Prettier"; that is, to make sure the tools have non-overlapping concerns.

**Comment by wincent** [comment]
Forgot to mention that by having the tools properly separated, we can use Prettier to format more than just JS. Like [here in liferay-js-themes-toolkit](https://github.com/liferay/liferay-js-themes-toolkit/blob/744343474eb3fd75c00ce3ef9d99cd72900797e0/package.json#L15), for example, where we use it to keep formatting errors out of our JSON and Markdown too.

**Comment by bryceosterhaus** [comment]
Is there really ever a reason where we don't want to use eslint but we want to use prettier? For the markdown and JSON example, those can also be handled by `prettier-eslint`. I understand they have different concerns at times, but there is quite a bit of overlap with any of the `--fix` related lint rules. Personally, I've never had issues combining them, whereas in the past I have had issues where I either forgot to run lint, but I ran format, or vice-versa.

I guess I don't see a _practical or tangible_ reason why we shouldn't just use `prettier-eslint` over `prettier` + `eslint`. I understand there are differences between them, but at the end of the day I just want to format everything in one step.

If we do decide to use them individually though, we should probably move this conversation up a level and then enforce using it across all infra projects outside of portal.

**Comment by wincent** [comment]
It may be a bit philosophical — and I know you asked for practical reasons — but I want linting and formatting to be separate because it's more in keeping with [the Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) ("Write programs that do one thing and do it well", "Write programs to work together") and that enables me to choose how and when to combine them together. For example, person A may want to configure their editor to auto-format on save but may want to manually review lint fixes. Person B may want everything to happen automatically by running a single "fix" command. If we bind the tools together then we rob people of that choice. Personally, for me, the fact that formatting only changes the way the code looks (for the most part, Prettier won't change the AST) puts it in a category of changes that I don't want to review to closely, but lint fixes I *do* want to review, and if I can't perform those steps separately I can't do that kind of differentiated review.

prettier-eslint-cli increases [our dependency footprint](https://github.com/prettier/prettier-eslint-cli/blob/44a8fc544045c29bc6924d148aee4419db811f23/package.json#L23-L42), making it more likely that we'll see issues in `yarn audit`/`npm audit` reports or that we'll have to pull down an upstream fix. Note that when I removed prettier-eslint-cli in a few of repos, it took hundreds of lines out of the lock-file each time: 

- https://github.com/liferay/liferay-amd-loader/pull/194/commits/30e1dfdf1b516b147d890834fe303b0cbc507fcd (2 files changed, 7 insertions(+), 959 deletions(-))
- https://github.com/liferay/liferay-npm-build-tools/pull/290/commits/a11a7c7189291ef192f9e59b7c61e74087bf74ac (2 files changed, 6 insertions(+), 891 deletions(-))
- https://github.com/liferay/liferay-js-themes-toolkit/commit/913829d497d4f4a1a93f7c35034972f91a29025b (1 file changed, 15 insertions(+), 554 deletions(-))

**Comment by bryceosterhaus** [comment]
haha yeah I guess at the end of the day it really just comes down to philosophy. I don't have that much attachment for `prettier-eslint` other than it just working fine for me in the past. I'm sure I can configure my dev environment to work the same with `prettier` and `eslint` separate so I'm fine with your suggestion.  I'll go ahead and re-open this issue so that we can use this for swapping out `prettier-eslint`.

**Comment by bryceosterhaus** [comment]
why you gotta close my issues like that? :smile:
