### ISSUE TITLE
Enforce trailing commas

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-npm-tools#380]
Originally requested [here](https://github.com/liferay/liferay-frontend-guidelines/issues/120) and green-lighted [here](https://github.com/liferay/liferay-frontend-guidelines/issues/120#issuecomment-585834606).

**Comment by wincent** [comment]
@jbalsas: Did you ever end up asking brianchandotcom about this?

**Comment by jbalsas** [comment]
As it turns out, I never got around to bring this up... as per our offline conversation, I think we might not see an immediate return here, specially since we wouldn't be able to format JS in JSP this way, so maybe it's best to document this limitation and park this for now?

Full disclosure, this particular feature is one of the ones I struggle with the most... but I wouldn't block it if the majority felt positively about it.

**Comment by p2kmgcl** [comment]
I don't like trailing commas :laughing:, I thought it would be useful to have them in portal. If no one else wants to have them we can ignore this.

**Comment by wincent** [comment]
I feel a bit stupid.

[This MDN page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas) claims that we *can* use trailing commas in IE9 and above, so I was wrong about this not being safe to put in our JSPs. This page from incredibly trustworthy/legendary JS educator Axel Rauschmayer also corroborates that only IE 8 doesn't support it...

Evidently, I was thinking of [this problem](https://github.com/brianchandotcom/liferay-portal/pull/79731#issuecomment-543540235) in JSP, which is precisely the opposite of what we're talking about here — that the *lack* of trailing commas in JSP was actually *causing* us problems when it came to conditional execution vs formatting...  🤦‍♂️
