### ISSUE TITLE
Add a --with-changelog option to the script that generates the changelog automatically

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-npm-tools#421]
The switch would make publish run the following steps:

1) npx liferay-changelog-generator --version=xxx (or without --version if we also implement #408)
2) git add -p
3) continue with liferay-js-publish as usual

Then, if someone wants to configure a project with changelog support she would put the following in `package.json`:

```json
{
	"scripts": {
		"postversion": "npx liferay-js-publish --with-changelog",
		"preversion": "yarn ci",
	}
}
```

**Comment by wincent** [comment]
> npx liferay-changelog-generator --version=xxx (or without --version if we also implement #408)

Not sure if this is what you were thinking or not, but just in case it isn't...

Just to clarify the purpose of #408: it's not to relieve you of the need to pass `--version` in general; it's so that in a monorepo that uses independent versioning (eg. tags of the form `liferay-some-package/v1.2.3`) you can pass `--version=v1.2.3` or `--version=1.2.3` and we'll coerce it into the desired `--version=liferay-some-package/v1.2.3` instead of you having to do it manually. This is possible only in the presence of per-package `.yarnrc` files.

By the time `liferay-js-publish` runs, the user has already run `yarn version`, so we can grab the version number from the `package.json` and pass it along. We'll still need `--version` though. (With the prefix from `.yarnrc.` if applicable if #408 isn't implemented yet, or without it if it has been implemented.)

Agreed that controlling this via a command-line switch is the right call, and that we need some kind of user intervention (either a prompt or a `git add -p` etc).

**Comment by izaera** [comment]
I'm not sure we can take the version from the package.json when running the changelog because it would be run `preversion`, not `postversion`, so we have to take it from the CLI. 

However, we provide it just once and use it for the changelog and yarn.

If I understood your comment correctly, then we don't need #408 to do this one because we will need to pass `--version` anyway.

**Comment by izaera** [comment]
So, my initial comment is wrong. It would be configured like this:

```json
{
	"scripts": {
		"release": "npx liferay-js-publish --with-changelog",
		"preversion": "yarn ci"
	}
}
```

And no `post-version` at all....

Does that make sense?
```

**Comment by izaera** [comment]
If we want to leave it with `postversion` we need two scripts or two invocations of `liferay-js-publish`, like this:

```json
{
	"scripts": {
		"release": "npx liferay-js-publish --changelog",
		"preversion": "npx liferay-js-publish",
		"preversion": "yarn ci"
	}
}
```

**Comment by wincent** [comment]
> I'm not sure we can take the version from the package.json when running the changelog because it would be run `preversion`, not `postversion`, so we have to take it from the CLI.

Might be able to get it from the `process.env`, because I am pretty sure that Yarn will pass something... let's see:

For example, test project `package.json`:

```json
{
  "name": "tmp.krFbMRQ2",
  "version": "1.0.1",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "preversion": "echo preversion; export",
    "version": "echo version; export",
    "postversion": "echo version; export"
  }
}
```

[Output of `yarn version --patch`](https://gist.github.com/wincent/b34fdd8f0955a8cba50dd7eb921a4ea0)

Note `npm_package_version` value:

- `preversion`: 1.0.0
- `version`: 1.0.1
- `postversion`: 1.0.1

> However, we provide it just once and use it for the changelog and yarn.
> 
> If I understood your comment correctly, then we don't need #408 to do this one because we will need to pass `--version` anyway.

I would like to be able to publish releases by running exactly one command: `yarn version`, so let's try to preserve that property in all this.

> If we want to leave it with `postversion` we need two scripts or two invocations of `liferay-js-publish`

Two invocations of the same tool sounds pretty terrible, even if hidden inside `scripts`.

We could invert the order, such that the one that must run first (`liferay-changelog-generator`) is the one that bumps the version number (ie. by offering to invoke `yarn version`) but the truth is I am liking the way things were more and more: two invocations, two tools that do exactly one simple thing each, and we less awkward coupling between tools. At the end of the day, how bad is it that the release process is this?:

```
liferay-changelog-generator --version=$VERSION
git add -p
yarn version --new-version=$VERSION
```

**Comment by wincent** [comment]
Actually, given the above, [seeing that `version`](https://docs.npmjs.com/misc/scripts):

> version: Run AFTER bumping the package version, but BEFORE commit.

It might be as simple as:

```
"scripts": {
	"preversion": "yarn ci",
        "version": "npx liferay-js-changelog-generator",
	"postversion": "npx liferay-js-publish",
}
```

And we just do #408 and teach liferay-js-chaneglog-generator to read from `npm_package_version` in the absence of an explicit `--version` tag.

I'd really like to avoid complecting these simple tools if possible.

**Comment by wincent** [comment]
What's missing from there is probably this:

```
"scripts": {
	"preversion": "yarn ci",
        "version": "npx liferay-js-changelog-generator --commit",
	"postversion": "npx liferay-js-publish",
}
```

Where `--commit` runs `git add -p $CHANGELOG.md` for you, basically. The only thing I am not sure of is how you would abort in the evident that you didn't like the changes and it was too hard to edit them inside `git add -p`... Maybe we can catch an interrupt (`C-c`) or something, or — probably better — add a confirmation prompt. 🤔

**Comment by izaera** [comment]
Confirmation prompt looks good :+1: and it's safer and more evident than `Ctrl+C`ing.

Regarding:

> At the end of the day, how bad is it that the release process is this?:
> liferay-changelog-generator --version=$VERSION
> git add -p
> yarn version --new-version=$VERSION

It's not that it's so bad, but if we make it possible to release versions running one single command that guides the user through the steps we don't need to:

1) write and maintain any release section in CONTRIBUTING.md (other than "just run yarn version")
2) remember anything when doing a release
3) teaching anybody how to do a release

I especially like fixing 2 because I consistently do something wrong when doing any manual step in a release. It is probably a limitation in my brain, but given that I have to be in the team (at least for now) we should provide some way to mitigate it.

**Comment by wincent** [comment]
Think I've boiled all this down to: https://github.com/liferay/liferay-npm-tools/issues/432 — so closing this one.
