### ISSUE TITLE
Add yarn "preversion" and "postversion" scripts to semi-automate publishing

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-npm-tools#50]
Based on discussion [over here](https://github.com/liferay/liferay-npm-tools/pull/49#discussion_r269610927) we might consider adding [some "postversion" scripts](https://yarnpkg.com/lang/en/docs/cli/version/) to make cutting releases a little bit easier.

They could be something like:

```json
{
  "scripts": {
    "preversion": "yarn format:check && yarn test",
    "postversion": "git push upstream master --follow-tags && yarn publish"
  }
}
```

or something like that. You'd then publish with `yarn version --minor` etc. I am a bit scared of running two publish operations (a `git push` and a `yarn publish`) like that, but perhaps with some extra checks (like ensuring you're on the "stable" branch etc) would make it feel a bit safer.

In this repo where we need tags of the form "package-name/version" we might need to add a layer of wrapping to ensure the correct format. Or perhaps `yarn config set version-tag-prefix "package-name/v"` and `yarn config set version-git-message "package-name/v%s"` would suffice.

**Comment by bryceosterhaus** [comment]
One issue I see with this is hardcoding the `upstream` remote. I sometimes like to use `github` at my remote name. Might not be a major issue, but I could see it coming up.

> I am a bit scared of running two publish operations (a git push and a yarn publish)
We also should probably check correct permissions to both the git repo and npm package itself. I know in the past I have run into issues when combining both if I am not logged in to the CLI or incorrect permissions.

One other possibility to help automate some of this would be to use Github actions. I've seen other repos do this, although I'm not sure about pain points with it yet since GH actions are relatively new.

**Comment by wincent** [comment]
Yeah, I have the same thought about `upstream`. For example, in most of my checkouts, I actually have `upstream` which uses an HTTPS URL and `upstream-rw` (read-write) that uses an SSH URL, to make it harder for me to accidentally push directly. And then there will be random clones where it ends up being `origin` or `github`. 🤦‍♂️

I think the way to make this agnostic would actually be to put in a wrapper script that inspected the output of `git remote -v` and if it can't find the remote it is looking for complains and tells you to set one up.
