### ISSUE TITLE
I'd like to configure which globs get sent to CSF

### ISSUE THREAD

**Issue by drewbrokke** [liferay/liferay-npm-tools#55]
CSF complains about not being able to find css and soy files, which makes sense because I don't have any, but I can't prevent `liferay-npm-scripts` from passing those globs to csf.

Example errors:
```
File does not exist: /Users/drewbrokke/Documents/liferay/liferay-portal/modules/apps/users-admin/users-admin-web/src/**/*.css

File does not exist: /Users/drewbrokke/Documents/liferay/liferay-portal/modules/apps/users-admin/users-admin-web/src/**/*.soy
```

**Comment by bryceosterhaus** [comment]
Possible solutions.

1. Add additional field in config such as `lintIgnore` which allows you to ignore certain globs.

- Pros: Not a breaking change. Explicit API
- Cons: Having both include and ignore globs can be pretty messy both for the user and for scripts themselves. Checking two globs against one another is not very easy.

2. When a user provides its own `format` and `lint` globs, we override instead of merge with the default values. We may also want to investigate using js file for config, this would allow importing the default values from `liferay-npm-scripts`.

- Pros: Easier to implement. Likely more performant than 1. Only one place to check globs.
- Cons: Breaking change. Not straight forward for user on which configs will be merged and with configs will be overridden.

Personally I think the second option is best, so long as we can make it clear to users on which configurations are overridden and which are merged. The first option is straight forward but doesn't scale well. I'm imagining two arrays of globs, which won't be clear on what is actually checked and which is not.

@wincent @izaera What are your guys' thoughts on this? Definitely is something we want to fix, but it causes bigger questions to be asked when it comes to merging vs overriding configuration.

**Comment by jbalsas** [comment]
Based on my current fiddlings with DXPs build system I'm lining more with remove options rather than provide additional levels of freedom. 

In such a big project, as we're seeing, it's easy to get misconfigured or outdated modules, wrong build configurations, unconventional project layouts or neglected formatting settings.

All in all, those were some of the reasons we kicked off this project, so for this case, and reading between the lines of @drewbrokke comment I'd say we should make `csf` a bit smarter and just keep it quiet if a glob doesn't match. We want to enforce formatting usage on our specific globs and avoid deviance at least to get started and until we get everything under control. 

After that, I'd explore this again if necessary, although the "exclussions" pattern might be a better marker for "hey, I'm not following expected patterns here, use this as a flag to remind you to come back and look into this". Otherwise, the glob is easily confused with the default behaviour rather than with a specific exception that should likely be corrected.

wdt?

**Comment by drewbrokke** [comment]
If it makes a difference, this does not break my build.  It's simply a warning I'd rather not see, so it's not mission-critical.

**Comment by wincent** [comment]
I believe this should be resolved now by https://github.com/liferay/liferay-npm-tools/pull/76 so I'll close this but please let me know if I'm mistaken.
